---
name: Uplift Merges
on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: Dry run
        default: true

jobs:
  uplift:
    name: Uplift
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run uplift script
        env:
          GH_TOKEN: ${{ github.token }}
          DRYRUN: ${{ inputs.dryRun && '' || '--no-dry-run' }}
          BRANCH: ${{ github.ref_name }}
        run: |
          bash scripts/uplift-merges.sh $DRYRUN --$BRANCH
